"""add repo head foreign key constraints

Revision ID: 236a2ee7507c
Revises: 2f3225982219
Create Date: 2023-06-17 16:42:14.131887

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "236a2ee7507c"
down_revision = "2f3225982219"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repos", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_repos_id_commits"),
            "commits",
            ["id", "head_commit_id"],
            ["repo_id", "id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repos", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_repos_id_commits"), type_="foreignkey")

    # ### end Alembic commands ###
