"""add comit authored and committed datetime fields

Revision ID: 2f3225982219
Revises: 8894f8ab014f
Create Date: 2023-06-17 16:33:04.739269

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f3225982219"
down_revision = "8894f8ab014f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("commits", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("authored_datetime", sa.DateTime(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("committed_datetime", sa.DateTime(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("commits", schema=None) as batch_op:
        batch_op.drop_column("committed_datetime")
        batch_op.drop_column("authored_datetime")

    # ### end Alembic commands ###
