"""fix repo id autoincrement

Revision ID: 802a3b210f33
Revises: 236a2ee7507c
Create Date: 2023-06-17 16:53:18.116002

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "802a3b210f33"
down_revision = "236a2ee7507c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
