"""fix head_commit_id type

Revision ID: a904ab0ac9e5
Revises: afbd7a9b71c1
Create Date: 2023-06-17 15:57:06.907896

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a904ab0ac9e5"
down_revision = "afbd7a9b71c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repos", schema=None) as batch_op:
        batch_op.drop_constraint("fk_repos_head_commit_id_commits", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_repos_id_commits"),
            "commits",
            ["id", "head_commit_id"],
            ["repo_id", "id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repos", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_repos_id_commits"), type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_repos_head_commit_id_commits", "commits", ["head_commit_id"], ["id"]
        )

    # ### end Alembic commands ###
