"""make chunk start required

Revision ID: ad467cc16a19
Revises: fa9bc2eb01f4
Create Date: 2023-07-01 11:14:06.535939

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ad467cc16a19"
down_revision = "fa9bc2eb01f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.alter_column("start", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.alter_column("start", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
