"""add repo.head_commit field

Revision ID: afbd7a9b71c1
Revises: 1528c99f48d2
Create Date: 2023-06-17 15:42:28.117402

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "afbd7a9b71c1"
down_revision = "1528c99f48d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("commits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("author_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("author_email", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("committer_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("committer_email", sa.String(), nullable=True))

    with op.batch_alter_table("repos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("head_commit_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_repos_head_commit_id_commits"),
            "commits",
            ["head_commit_id"],
            ["id"],
        )
        batch_op.drop_column("head")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("head", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("fk_repos_head_commit_id_commits"), type_="foreignkey"
        )
        batch_op.drop_column("head_commit_id")

    with op.batch_alter_table("commits", schema=None) as batch_op:
        batch_op.drop_column("committer_email")
        batch_op.drop_column("committer_name")
        batch_op.drop_column("author_email")
        batch_op.drop_column("author_name")

    # ### end Alembic commands ###
