[tool.black]
exclude = "build"

[tool.isort]
profile = "black"
known_third_party = ["alembic"]
src_paths = ["codal", "experiments", "tests"]

[tool.pyright]
exclude = ["build", "tests/test_migrations.py"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*declarative_base.*:DeprecationWarning:langchain",
]
markers = [
    "serial: tests to avoid using with pytest-xdist",
]
