"""Add chunks.text

Revision ID: 056717e4cd6d
Revises: 32fab6cd6262
Create Date: 2023-06-03 18:36:48.582560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056717e4cd6d'
down_revision = '32fab6cd6262'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'text')
    # ### end Alembic commands ###
