"""First revision

Revision ID: 32fab6cd6262
Revises: 
Create Date: 2023-06-03 18:35:46.887416

"""
import sqlalchemy as sa

import codal
from alembic import op

# revision identifiers, used by Alembic.
revision = "32fab6cd6262"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orgs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orgs_id"), "orgs", ["id"], unique=False)
    op.create_index(op.f("ix_orgs_name"), "orgs", ["name"], unique=True)
    op.create_table(
        "repos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("zip_path", codal.models.FilePath(), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["orgs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "name"),
        sa.UniqueConstraint("zip_path"),
    )
    op.create_index(op.f("ix_repos_id"), "repos", ["id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=True),
        sa.Column("path", codal.models.FilePath(), nullable=True),
        sa.Column("text", sa.String(), nullable=True),
        sa.Column("num_tokens", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repo_id"],
            ["repos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repo_id", "path"),
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=True),
        sa.Column("start", sa.Integer(), nullable=True),
        sa.Column("end", sa.Integer(), nullable=True),
        sa.Column("embedding", codal.models.NumpyArray(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "end"),
        sa.UniqueConstraint("document_id", "start"),
    )
    op.create_index(op.f("ix_chunks_id"), "chunks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunks_id"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_repos_id"), table_name="repos")
    op.drop_table("repos")
    op.drop_index(op.f("ix_orgs_name"), table_name="orgs")
    op.drop_index(op.f("ix_orgs_id"), table_name="orgs")
    op.drop_table("orgs")
    # ### end Alembic commands ###
