"""add composite indexes

Revision ID: 3812ca2ef6c8
Revises: 514d51e83930
Create Date: 2023-06-17 16:23:36.464701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3812ca2ef6c8'
down_revision = '514d51e83930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_versions_document_id', type_='unique')
        batch_op.create_index('document_id', ['commit_id'], unique=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_documents_repo_id', type_='unique')
        batch_op.create_index('repo_id', ['path'], unique=True)

    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.alter_column('head_commit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('uq_repos_org_id', type_='unique')
        batch_op.create_index('org_id', ['name'], unique=True)
        batch_op.drop_constraint('fk_repos_id_commits', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_repos_head_commit_id_commits'), 'commits', ['head_commit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_repos_head_commit_id_commits'), type_='foreignkey')
        batch_op.create_foreign_key('fk_repos_id_commits', 'commits', ['id', 'head_commit_id'], ['repo_id', 'id'])
        batch_op.drop_index('org_id')
        batch_op.create_unique_constraint('uq_repos_org_id', ['org_id', 'name'])
        batch_op.alter_column('head_commit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('repo_id')
        batch_op.create_unique_constraint('uq_documents_repo_id', ['repo_id', 'path'])

    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index('document_id')
        batch_op.create_unique_constraint('uq_document_versions_document_id', ['document_id', 'commit_id'])

    # ### end Alembic commands ###
