"""Version documents and repo

Revision ID: e8a7160c4e8d
Revises: 056717e4cd6d
Create Date: 2023-06-04 11:28:02.048066

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e8a7160c4e8d"
down_revision = "056717e4cd6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("head", sa.String(), nullable=True))
        batch_op.create_unique_constraint(
            "unique__document__repo_path_head", ["repo_id", "path", "head"]
        )

    with op.batch_alter_table("repos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("head", sa.String(), nullable=True))
        batch_op.drop_column("zip_path")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("zip_path", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("head")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint("unique__document__repo_path_head", type_="unique")
        batch_op.drop_column("head")

    # ### end Alembic commands ###
