"""Add document processed bool

Revision ID: edff9d4dd28f
Revises: e8a7160c4e8d
Create Date: 2023-06-04 11:28:46.475973

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "edff9d4dd28f"
down_revision = "e8a7160c4e8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("processed", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_column("processed")

    # ### end Alembic commands ###
