"""make repo default_branch nullable

Revision ID: fa9bc2eb01f4
Revises: ba31d3d85648
Create Date: 2023-06-19 07:43:51.863667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9bc2eb01f4'
down_revision = 'ba31d3d85648'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.alter_column('default_branch',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repos', schema=None) as batch_op:
        batch_op.alter_column('default_branch',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
