# Generated by Django 4.2.1 on 2023-06-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="zip_path",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="embedding",
            name="hash",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="embedding",
            name="path",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="repo",
            name="name",
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("document", "start"), name="unique_chunk_document_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="chunk",
            constraint=models.UniqueConstraint(
                fields=("document", "end"), name="unique_chunk_document_end"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("repo", "path"), name="unique_document_repo_path"
            ),
        ),
    ]
