# Generated by Django 4.2.1 on 2023-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codal", "0002_repo_zip_path_alter_embedding_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="name",
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name="repo",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_repo_org_name"
            ),
        ),
    ]
